### ISSUE TITLE
FE - Support two types of rewards

### ISSUE THREAD

**Issue by bendavidelad** [CalculatorMiluim/Calculator-Miluim#21]
In the back-end we have two types of rewards:
1. financial_reward (int) - for example, 3500
2. other_reward (str) - for example, ״ימי התרעננות״

currently in the front-end we show only financial reward even though some benefits doesn't include it.
the logic should be as follows:

if financial_reward is not 0 - show it
if other_reward is not empty string - show it

**Comment by NL1987ULES** [comment]
Other rewards should be in a different section with an appropiate name

**Comment by danielbenedykt** [comment]
added information , here is an example

![image](https://github.com/CalculatorMiluim/Calculator-Miluim/assets/307628/9be836ed-4bff-4e69-9e5d-098020c15521)
