### ISSUE TITLE
FE + BE - Add the ability to add more dates range

### ISSUE THREAD

**Issue by NL1987ULES** [CalculatorMiluim/Calculator-Miluim#31]

**Comment by danielbenedykt** [comment]
@NL1987ULES 
can you add more details?
The idea is to have many dates,   and add the days all together to then calculate the benefits ?

**Comment by NL1987ULES** [comment]
The idea is to add a button stating "add more date".
And then the user will be able to choose more dates with type.
Then send to the BE the dates as a list.
I think there is a UI look in the figma

**Comment by danielbenedykt** [comment]
waiting on the definition of date component on ticket:  https://github.com/CalculatorMiluim/Calculator-Miluim/issues/26

**Comment by danielbenedykt** [comment]
done
