### ISSUE TITLE
improve Bot

### ISSUE THREAD

**Issue by danielbenedykt** [CalculatorMiluim/Calculator-Miluim#38]
1- start should be like other bots,  with start button and nothing else do  .   DONE
2- validate response from user, user can write anything and the bot moves forward   . DONE
3- its fine to "replace the buttons" and not continue like a normal conversation ?   . Its the way it was intended  DONE
4- refactor bot secret code . Pending
5- update menu. DONE

**Comment by danielbenedykt** [comment]
> 1- start should be like other bots, with start button and nothing else do

This is already happening the first time (to test you can delete the history without blocking the bot) and start again
What we should do to restart , is add a menu like other bots
There are different ways to do it, so please @ari-gen-x  talk about it
https://stackoverflow.com/questions/72594564/how-can-i-add-menu-button-in-telegram-bot

**Comment by danielbenedykt** [comment]
@NL1987ULES 
I added a new menu,  attached screenshot
![94112d0b-b641-427c-804a-154c05aaff88](https://github.com/CalculatorMiluim/Calculator-Miluim/assets/307628/e13402bb-f279-474c-9df0-e5284fe548c5)

I will need the following texts:

a) Main menu/start or whatever you want it to call it
b) help  (the title)
c) help text  (the content you want to show when user press help button menu)

**Comment by NL1987ULES** [comment]
That can be in hebrew?

**Comment by danielbenedykt** [comment]
pending assistance on secret values
