### ISSUE TITLE
When choosing unevrsity "other" unable to continue and nothing is shown in UI

### ISSUE THREAD

**Issue by NL1987ULES** [CalculatorMiluim/Calculator-Miluim#56]
https://github.com/CalculatorMiluim/Calculator-Miluim/assets/54059009/4bfa9e9e-0e3a-4b3c-8710-a1cdb21b92fd

**Comment by danielbenedykt** [comment]
@NL1987ULES ,  thi value "other" seems to be only defined in the front end
its not defined in the backend.
should we remove it or add it in the backend and use it in the logic ?

**Comment by bendavidelad** [comment]
currently we have no benefits related to general students, so it doesn't affect anything for now.
I guess both options are valid for the moment, whatever takes less effort.
