### ISSUE TITLE
Add description on what being a commandor means

### ISSUE THREAD

**Issue by NL1987ULES** [CalculatorMiluim/Calculator-Miluim#64]
Need to add a hover option that explains what being a commandor means.

![image](https://github.com/CalculatorMiluim/Calculator-Miluim/assets/54059009/9a994b3f-9f3f-4349-ab2a-c6acb77d6430)

**Comment by danielbenedykt** [comment]
@NL1987ULES 
can you send me the text in hebrew so I can copy/paste ?

**Comment by NL1987ULES** [comment]
למפקדים מדרג המ״פ ומעלה המוכרים על ידי המדרג הפיקודי במדרגה א׳+, צוות אוויר, צוות ים ומפקדים אשר חלה עליהם מדיניות קיבוע זכויות מג״ד והינם משרתי מילואים פעילים ונמצאים על מינוי מזכה לפחות 90 ימים בשנה הקודמת
